# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import trading212_api_client
from trading212_api_client.paths.api_v0_equity_metadata_exchanges import get  # noqa: E501
from trading212_api_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV0EquityMetadataExchanges(ApiTestMixin, unittest.TestCase):
    """
    ApiV0EquityMetadataExchanges unit test stubs
        Exchange List  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
