# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

import unittest

import trading212_api_client
from trading212_api_client.model.place_order_error import PlaceOrderError
from trading212_api_client import configuration


class TestPlaceOrderError(unittest.TestCase):
    """PlaceOrderError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
