# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.limit_request import LimitRequest
from openapi_client import configuration


class TestLimitRequest(unittest.TestCase):
    """LimitRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
