# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.stop_request import StopRequest
from openapi_client import configuration


class TestStopRequest(unittest.TestCase):
    """StopRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
