# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from trading212_api_client.paths.api_v0_equity_orders_id.delete import CancelOrder
from trading212_api_client.paths.api_v0_equity_orders_id.get import OrderById
from trading212_api_client.paths.api_v0_equity_orders.get import Orders
from trading212_api_client.paths.api_v0_equity_orders_limit.post import PlaceLimitOrder
from trading212_api_client.paths.api_v0_equity_orders_market.post import PlaceMarketOrder
from trading212_api_client.paths.api_v0_equity_orders_stop_limit.post import PlaceStopOrder
from trading212_api_client.paths.api_v0_equity_orders_stop.post import PlaceStopOrder1


class EquityOrdersApi(
    CancelOrder,
    OrderById,
    Orders,
    PlaceLimitOrder,
    PlaceMarketOrder,
    PlaceStopOrder,
    PlaceStopOrder1,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
