# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from trading212_api_client.paths.api_v0_equity_pies.post import Create
from trading212_api_client.paths.api_v0_equity_pies_id.delete import Delete
from trading212_api_client.paths.api_v0_equity_pies_id_duplicate.post import DuplicatePie
from trading212_api_client.paths.api_v0_equity_pies.get import GetAll
from trading212_api_client.paths.api_v0_equity_pies_id.get import GetDetailed
from trading212_api_client.paths.api_v0_equity_pies_id.post import Update


class PiesApi(
    Create,
    Delete,
    DuplicatePie,
    GetAll,
    GetDetailed,
    Update,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
