# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from trading212_api_client import schemas  # noqa: F401


class ReportResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def dataIncluded() -> typing.Type['ReportDataIncluded']:
                return ReportDataIncluded
            downloadLink = schemas.StrSchema
            reportId = schemas.Int64Schema
            
            
            class status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "Queued": "QUEUED",
                        "Processing": "PROCESSING",
                        "Running": "RUNNING",
                        "Canceled": "CANCELED",
                        "Failed": "FAILED",
                        "Finished": "FINISHED",
                    }
                
                @schemas.classproperty
                def QUEUED(cls):
                    return cls("Queued")
                
                @schemas.classproperty
                def PROCESSING(cls):
                    return cls("Processing")
                
                @schemas.classproperty
                def RUNNING(cls):
                    return cls("Running")
                
                @schemas.classproperty
                def CANCELED(cls):
                    return cls("Canceled")
                
                @schemas.classproperty
                def FAILED(cls):
                    return cls("Failed")
                
                @schemas.classproperty
                def FINISHED(cls):
                    return cls("Finished")
            timeFrom = schemas.DateTimeSchema
            timeTo = schemas.DateTimeSchema
            __annotations__ = {
                "dataIncluded": dataIncluded,
                "downloadLink": downloadLink,
                "reportId": reportId,
                "status": status,
                "timeFrom": timeFrom,
                "timeTo": timeTo,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataIncluded"]) -> 'ReportDataIncluded': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["downloadLink"]) -> MetaOapg.properties.downloadLink: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reportId"]) -> MetaOapg.properties.reportId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeFrom"]) -> MetaOapg.properties.timeFrom: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeTo"]) -> MetaOapg.properties.timeTo: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["dataIncluded", "downloadLink", "reportId", "status", "timeFrom", "timeTo", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataIncluded"]) -> typing.Union['ReportDataIncluded', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["downloadLink"]) -> typing.Union[MetaOapg.properties.downloadLink, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reportId"]) -> typing.Union[MetaOapg.properties.reportId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeFrom"]) -> typing.Union[MetaOapg.properties.timeFrom, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeTo"]) -> typing.Union[MetaOapg.properties.timeTo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["dataIncluded", "downloadLink", "reportId", "status", "timeFrom", "timeTo", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        dataIncluded: typing.Union['ReportDataIncluded', schemas.Unset] = schemas.unset,
        downloadLink: typing.Union[MetaOapg.properties.downloadLink, str, schemas.Unset] = schemas.unset,
        reportId: typing.Union[MetaOapg.properties.reportId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        timeFrom: typing.Union[MetaOapg.properties.timeFrom, str, datetime, schemas.Unset] = schemas.unset,
        timeTo: typing.Union[MetaOapg.properties.timeTo, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReportResponse':
        return super().__new__(
            cls,
            *_args,
            dataIncluded=dataIncluded,
            downloadLink=downloadLink,
            reportId=reportId,
            status=status,
            timeFrom=timeFrom,
            timeTo=timeTo,
            _configuration=_configuration,
            **kwargs,
        )

from trading212_api_client.model.report_data_included import ReportDataIncluded
