# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from trading212_api_client import schemas  # noqa: F401


class ReportDataIncluded(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            includeDividends = schemas.BoolSchema
            includeInterest = schemas.BoolSchema
            includeOrders = schemas.BoolSchema
            includeTransactions = schemas.BoolSchema
            __annotations__ = {
                "includeDividends": includeDividends,
                "includeInterest": includeInterest,
                "includeOrders": includeOrders,
                "includeTransactions": includeTransactions,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["includeDividends"]) -> MetaOapg.properties.includeDividends: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["includeInterest"]) -> MetaOapg.properties.includeInterest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["includeOrders"]) -> MetaOapg.properties.includeOrders: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["includeTransactions"]) -> MetaOapg.properties.includeTransactions: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["includeDividends", "includeInterest", "includeOrders", "includeTransactions", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["includeDividends"]) -> typing.Union[MetaOapg.properties.includeDividends, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["includeInterest"]) -> typing.Union[MetaOapg.properties.includeInterest, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["includeOrders"]) -> typing.Union[MetaOapg.properties.includeOrders, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["includeTransactions"]) -> typing.Union[MetaOapg.properties.includeTransactions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["includeDividends", "includeInterest", "includeOrders", "includeTransactions", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        includeDividends: typing.Union[MetaOapg.properties.includeDividends, bool, schemas.Unset] = schemas.unset,
        includeInterest: typing.Union[MetaOapg.properties.includeInterest, bool, schemas.Unset] = schemas.unset,
        includeOrders: typing.Union[MetaOapg.properties.includeOrders, bool, schemas.Unset] = schemas.unset,
        includeTransactions: typing.Union[MetaOapg.properties.includeTransactions, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReportDataIncluded':
        return super().__new__(
            cls,
            *_args,
            includeDividends=includeDividends,
            includeInterest=includeInterest,
            includeOrders=includeOrders,
            includeTransactions=includeTransactions,
            _configuration=_configuration,
            **kwargs,
        )
