# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v0_equity_account_info.get import Account
from openapi_client.paths.api_v0_equity_account_cash.get import AccountCash


class AccountDataApi(
    Account,
    AccountCash,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
