# coding: utf-8

"""
    Trading212 Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v0_history_dividends.get import Dividends
from openapi_client.paths.api_v0_history_exports.get import GetReports
from openapi_client.paths.api_v0_equity_history_orders.get import Orders1
from openapi_client.paths.api_v0_history_exports.post import RequestReport
from openapi_client.paths.api_v0_history_transactions.get import Transactions


class HistoricalItemsApi(
    Dividends,
    GetReports,
    Orders1,
    RequestReport,
    Transactions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
